# Generated by Django 5.1.7 on 2025-03-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='oeder_date',
            new_name='order_date',
        ),
    ]
