# Generated by Django 5.1.4 on 2025-04-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_rename_oeder_date_orderplaced_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
    ]
