# Generated by Django 5.1.4 on 2025-04-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_remove_customer_state_remove_customer_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
